name: Build Electron App and Python Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies and build backend
        run: |
          cd python_backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --name retouch_backend --onefile --hidden-import=mediapipe \
            --hidden-import=cv2 --hidden-import=matplotlib \
            --hidden-import=matplotlib.backends.backend_tkagg \
            --collect-data mediapipe --collect-all mediapipe \
            --add-data "models:models" --noconfirm --clean main.py
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build Electron (macOS)
        run: |
          cd electron_app
          npm install
          npm run build:mac
          mkdir -p "dist/mac/Retouch App.app/Contents/Resources/backend"
          # PyInstaller で生成されたバイナリ (拡張子なし)
          cp ../python_backend/dist/retouch_backend \
             "dist/mac/Retouch App.app/Contents/Resources/backend/"
